### ISSUE TITLE
 runtime error: slice bounds out of range [:18] with capacity 16

### ISSUE THREAD

**Issue by shaikhtalal** [twpayne/go-geom#146] opened 2020-04-23 10:07 UTC
While creating convexhull the function crashed ConvexHullFlat. Please find the stack trace along with sample test case. @twpayne 

runtime/debug.Stack(0x210e2b8, 0xc0004d2a00, 0x2)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/RichardKnop/machinery/v1/tasks.(*Task).Call.func1(0xc000245cc8, 0xc0004ba780)
        /home/talal/go/pkg/mod/github.com/!richard!knop/machinery@v1.6.5/v1/tasks/task.go:130 +0xbc
panic(0x12819e0, 0xc0005009c0)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/twpayne/go-geom/xy.(*convexHullCalculator).computeOctRing(0xc000244d38, 0xc000628000, 0x782, 0x782, 0xc000244c01, 0xc000244cb0, 0x49b521)
        /home/talal/go/pkg/mod/github.com/twpayne/go-geom@v1.0.5-0.20190320002942-31a8a3d5e136/xy/convex_hull.go:242 +0x19b
github.com/twpayne/go-geom/xy.(*convexHullCalculator).reduce(0xc000244d38, 0xc000628000, 0x782, 0x782, 0x782, 0x782, 0xc000646000)
        /home/talal/go/pkg/mod/github.com/twpayne/go-geom@v1.0.5-0.20190320002942-31a8a3d5e136/xy/convex_hull.go:176 +0x67
github.com/twpayne/go-geom/xy.convexHullCalculator.getConvexHull(0x1, 0x2, 0xc000628000, 0x782, 0x782, 0x8e30, 0x0)
        /home/talal/go/pkg/mod/github.com/twpayne/go-geom@v1.0.5-0.20190320002942-31a8a3d5e136/xy/convex_hull.go:62 +0x2e2
github.com/twpayne/go-geom/xy.ConvexHullFlat(0x1, 0xc000628000, 0x782, 0x782, 0x2, 0x8e30)
        /home/talal/go/pkg/mod/github.com/twpayne/go-geom@v1.0.5-0.20190320002942-31a8a3d5e136/xy/convex_hull.go:44 +0xa1
tespkg.in/seismic-service/pkg/set.(*traceIndexer3D).writeConvexHull(0xc0002c4000, 0x161aee0, 0xc0004cc680, 0x0, 0x0)
        /home/talal/go/src/seismic-manager/pkg/set/segy_3d_indexer.go:794 +0x2ba
tespkg.in/seismic-service/pkg/set.(*traceIndexer3D).writeIndex(0xc0002c4000, 0x161aee0, 0xc0004cc680, 0x9, 0x0, 0x0)
        /home/talal/go/src/seismic-manager/pkg/set/segy_3d_indexer.go:935 +0x257
tespkg.in/seismic-service/pkg/set.IndexSEGYSet(0x1632320, 0xc00046ad20, 0x7f57c25c7888, 0xc000044e40, 0xc00025ccc0, 0x1, 0x1, 0xc0000c0f00, 0xc0000f2b80, 0xc0005734b0, ...)
        /home/talal/go/src/seismic-manager/pkg/set/index_segy_set.go:231 +0xdce
tespkg.in/seismic-service/server.(*seismicService).taskIndexSEGYSet(0xc000044420, 0x1632260, 0xc0000f2cc0, 0xc00025ccc0, 0x1, 0x1, 0xc000284000, 0x7d, 0xc00058c000, 0x63, ...)
        /home/talal/go/src/seismic-manager/server/index_segy_set.go:237 +0x6da
reflect.Value.call(0x119f9c0, 0xc00007c090, 0x13, 0x1329133, 0x4, 0xc0000c0d20, 0x4, 0x4, 0x4, 0x18, ...)
        /usr/local/go/src/reflect/value.go:460 +0x5f6
reflect.Value.Call(0x119f9c0, 0xc00007c090, 0x13, 0xc0000c0d20, 0x4, 0x4, 0x3, 0x3, 0xc00016e11c)
        /usr/local/go/src/reflect/value.go:321 +0xb4
github.com/RichardKnop/machinery/v1/tasks.(*Task).Call(0xc0004ba780, 0x0, 0x0, 0x0, 0x7f57c2545558, 0xc0005009c0)
        /home/talal/go/pkg/mod/github.com/!richard!knop/machinery@v1.6.5/v1/tasks/task.go:142 +0x25d
github.com/RichardKnop/machinery/v1.(*Worker).Process(0xc0000e78b0, 0xc000420000, 0x0, 0x0)
        /home/talal/go/pkg/mod/github.com/!richard!knop/machinery@v1.6.5/v1/worker.go:169 +0x389
github.com/RichardKnop/machinery/v1/brokers/redis.(*Broker).consumeOne(0xc0004040c0, 0xc00028a800, 0x73f, 0x73f, 0x1619120, 0xc0000e78b0, 0x0, 0x0)
        /home/talal/go/pkg/mod/github.com/!richard!knop/machinery@v1.6.5/v1/brokers/redis/redis.go:286 +0x241
github.com/RichardKnop/machinery/v1/brokers/redis.(*Broker).consume.func2(0xc0004040c0, 0xc00028a800, 0x73f, 0x73f, 0x1619120, 0xc0000e78b0, 0xc000408360, 0xc, 0xc0000a68a0)
        /home/talal/go/pkg/mod/github.com/!richard!knop/machinery@v1.6.5/v1/brokers/redis/redis.go:250 +0x6a
created by github.com/RichardKnop/machinery/v1/brokers/redis.(*Broker).consume
        /home/talal/go/pkg/mod/github.com/!richard!knop/machinery@v1.6.5/v1/brokers/redis/redis.go:249 +0x153 
INFO[0004] Failed processing task task_fae157f0-a03e-4504-9ff3-86636d5993c0. Error = runtime error: slice bounds out of range [:18] with capacity 16 

[geom_test.zip](https://github.com/twpayne/go-geom/files/4521708/geom_test.zip)

**Comment by jackielii** [comment] 2020-04-23 16:49
@shaikhtalal @twpayne I believe this is happening because the points returned by `calc.computeOctPts` is already the 8 distinct points. so the `copyTo` is already `8 * stride`, and panic happens when trying to extend the capacity to `9 * stride` when closing the ring.

Trying to push a naive fix. I still feel the problem is inside `calc.computeOctPts`

**Comment by jackielii** [comment] 2020-05-18 17:22
Hi @twpayne , thanks for looking into the PR #147. I agree that the fix is not correct. So I'll just extracted the minimal reproducible tests for you to check here: 

```go

func TestOctRingPanic(t *testing.T) {
	flat := []float64{
		1, 1,
		1, 2,
		2, 3,
		3, 3,
		4, 2,
		4, 1,
		3, 0,
		2, 0,
	}
	calc := convexHullCalculator{layout: geom.XYM, stride: 2}
	got := calc.computeOctRing(flat)
	expected := []float64{
		1, 1,
		1, 2,
		2, 3,
		3, 3,
		4, 2,
		4, 1,
		3, 0,
		1, 1,
	}
	if !reflect.DeepEqual(expected, got) {
		t.Fatalf("calc.computeOctRing failed. Expected \n\t%v\nbut was \n\t%v", expected, got)
	}
}
```

**Comment by twpayne** [comment] 2020-05-18 17:34
Thanks, however the test is also not correct.

`computeOctRing` is an internal method that implements the [Akl–Toussaint heuristic](https://en.wikipedia.org/wiki/Convex_hull_algorithms#Akl%E2%80%93Toussaint_heuristic). In the test, the expected value is incorrect.

**Comment by jackielii** [comment] 2020-05-18 17:44
> Thanks, however the test is also not correct.
> 
> `computeOctRing` is an internal method that implements the [Akl–Toussaint heuristic](https://en.wikipedia.org/wiki/Convex_hull_algorithms#Akl%E2%80%93Toussaint_heuristic). In the test, the expected value is incorrect.

Indeed! Thanks for the URL.

I suppose the valid part of the test is it will cause the panic the OP had

**Comment by chrisdinn** [comment] 2021-06-02 15:35
Looks to me like this  always panics when the octogon points are all unique. This algorithm will work fine by just dropping duplicates from the octogon, no need I can see to do the (somewhat confusing) copying that's in there now. Pushed a fix for review.

**Closed** 2021-06-02 16:22 UTC
Labels: bug

**Comment by RichDavis1** [comment] 2022-03-16 02:17
Currently experiencing this exact same bug. 

What's interesting is it works locally but not when performed on a lambda, everything is identical.

```
runtime error: slice bounds out of range [:18] with capacity 16: boundsError
[
{
    "path": "github.com/aws/aws-lambda-go@v1.19.1/lambda/errors.go",
    "line": 33,
    "label": "lambdaPanicResponse"
}
,
{
    "path": "github.com/aws/aws-lambda-go@v1.19.1/lambda/function.go",
    "line": 36,
    "label": "(*Function).Invoke.func1"
}
,
{
    "path": "runtime/panic.go",
    "line": 965,
    "label": "gopanic"
}
,
{
    "path": "runtime/panic.go",
    "line": 106,
    "label": "goPanicSliceAcap"
}
,
{
    "path": "github.com/twpayne/go-geom@v1.3.6/xy/convex_hull.go",
    "line": 240,
    "label": "(*convexHullCalculator).computeOctRing"
}
,
{
    "path": "github.com/twpayne/go-geom@v1.3.6/xy/convex_hull.go",
    "line": 174,
    "label": "(*convexHullCalculator).reduce"
}
,
{
    "path": "github.com/twpayne/go-geom@v1.3.6/xy/convex_hull.go",
    "line": 63,
    "label": "convexHullCalculator.getConvexHull"
}
,
{
    "path": "github.com/twpayne/go-geom@v1.3.6/xy/convex_hull.go",
    "line": 32,
    "label": "ConvexHull"
}
```
